export const text = {
  error: 'Error',
  overallLikes: 'Overall likes: ',
  maleLiked: 'Male liked: ',
  femaleLiked: 'Female liked: ',
  reset: 'Reset',
  homeCaps: 'HOME',
  characterCaps: 'CHARACTER',
  name: 'Name: ',
  birthDate: 'Birth date: ',
  gender: 'Gender: ',
  mass: 'Mass: ',
  hairColor: 'Hair color: ',
  skinColor: 'Skin color: ',
  addToLikedCaps: 'ADD TO LIKED',
  removeFromLikedCaps: 'REMOVE FROM LIKED',
}
